apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationery
  template:
    metadata:
      labels:
        app: stationery
    spec:
      containers:
      - name: stationery-container
        image: vikasrajput0112/stationery-app:v1
        ports:
        - containerPort: 80
